### ISSUE TITLE
13th Street, NPO Doc, NPO Humor TV and Syfy have ceased and several Horizon.tv IDs have changed.

### ISSUE THREAD

**Issue by antoniong** [tvgrabbers/tvgrabnlpy#65]
I got this message and and checked .Config. None of these are in my .Config. Yet I keep getting this message. 

Is running with --configure a must? I prefer not to do since I will have to retrace all the changes I made.

**Comment by kyl416** [comment]
Any changes you made to things like channel names or which channels are enabled will remain the same after you rerun configure. The xmltv id's will remain the same too, so you won't need to make any changes to the app/software you use the xmltv file with (i.e. MythTV, Kodi, NextPVR, etc)

Many horizon.tv IDs changed overnight because of the changes Ziggo made to their lineup. SBS 9, Disney Channel, Film1 Sundance, Ziggo Sport Golf, WDR, MyZen, Travel Channel, Comedy Central Extra, MTV Live HD, ATV Avrupa, Euro D, Euro Star and Samanyolu Avrupa all have new horizon.tv IDs. Several existing channels also now have horizon.tv IDs like E! and BBC First, and there's a few new channels now available like Fine Living and Food Network.

**Comment by hikavdh** [comment]
If you do not want to run configure, but want to get rid of the message, raise the value of data_version in your configuration to 15. That is what it compares to to trigger the message
