### ISSUE TITLE
Nothing at all is being fetched, not even with 2.2.16

### ISSUE THREAD

**Issue by pensionado** [tvgrabbers/tvgrabnlpy#68]
Since yesterday morning nothing is being fetched / generated by the grabber.  First thought it was a 2.2.17 problem, so went back to 2.2.16 same problem. Then tried on another computer where I hadn't used tvgrab for over a week, same problem. Attached xmltv directory of that last test
[.xmltv.tar.gz](https://github.com/tvgrabbers/tvgrabnlpy/files/441024/default.xmltv.tar.gz)

**Comment by TD-er** [comment]
Here the same problem and I was still running 2.2.13
Tried 2.2.17 and no luck.

**Comment by hikavdh** [comment]
Sorry it seems that an earlier bug on disabling a source is coming back, while it shouldn't. I re-enabled it. You now will only get errors on the changed format on nieuwsblad.be.

**Comment by hikavdh** [comment]
It gets weirder, the date error on nieuwsblad.be has gone. It looks like they tried a different format and reverted it. I keep an eye on it, but for now in 2.2.17 all seems to work. Even the url change is reverted, so also 2.2.16 should work with nieuwsblad.be (they use a weekday or vandaag, morgen or overmorgen) in the url. Since a few days they would not accept for instance maandag instead of vandaag, but they do again.)
